### ISSUE TITLE
where to go from here?

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [intellectsoft-uk/MssqlBundle#19]
if this bundle is abandonded, is there any other common bundle for MS SQL /Doctrine, possible for Symfony 3 or the likes?

Edit: It looks like doctrine supports sql server now, did it not support it when this was created?

**Comment by snsanich** [comment]
Doctrine did not support MS SQL 4-7 years ago, if I remember correctly.

You did not write version of MS SQL server. First of all, you might be surprised how mssql differ from version to version (I mean API, SDK, not a functionality).

In my experience, you need to specify for yourself a mssql driver you are looking for. Than you might find a bundle.

Take a look on https://docs.microsoft.com/en-us/sql/connect/php/microsoft-php-driver-for-sql-server. Try to use and test mssql driver as described on page. Then you will know what to search.
