### ISSUE TITLE
Could you tag a release?

### ISSUE THREAD

**Issue by kbond** [intellectsoft-uk/MssqlBundle#8]

**Comment by rogeriolino** [comment]
:+1: 

Generating release will speed up the composer update

**Comment by kbond** [comment]
@rogeriolino I am not sure if you require features in this library that aren't in that one but I switched to https://github.com/realestateconz/MssqlBundle which has releases.

**Comment by rogeriolino** [comment]
@kbond I'm using realestateconz/MssqlBundle too, just because releases.

However the base repo is more outdated than this fork.

**Comment by kbond** [comment]
Closing as stale.
